export const HEROES_FETCHING = 'HEROES_FETCHING';
export const HEROES_FETCHED = 'HEROES_FETCHED';
export const HEROES_FETCHING_ERROR = 'HEROES_FETCHING_ERROR';
export const DELETE_HERO = 'DELETE_HERO';
export const CREATE_HERO = 'CREATE_HERO';
