export const FILTERS_FETCHING = 'FILTERS_FETCHING';
export const FILTERS_FETCHED = 'FILTERS_FETCHED';
export const FILTERS_FETCHING_ERROR = 'FILTERS_FETCHING_ERROR';
export const SET_ACTIVE_FILTER = 'SET_ACTIVE_FILTER';
